# host
hostname: host1

# network interface to capture data on. 
interface: ens18

# number of packet processing threads
threads: 4

# Use local_networks to determine if a packet is inbound or outbound.
local_networks_as_direction: 0

local_networks:
  - 192.168.20.0/24
  - 192.168.1.0/24

# capture modules
foreach:

  # dns module
  dns:
    enabled: 1
    #metrics:
    #  - question
    #  - question_type
    #  - answer
    #  - rtt

  # flow stats module
  flow_statistics:
    enabled: 0
    # how often to output results in millseconds
    output_interval: 60000
    metrics:
      - byte_count
      - packet_count
      - flow_count
      - ip_count

  # statistics module
  stats:
    enabled: 0
    output_interval: 60000
    metrics:
      - byte_count
      - packet_count

# output modules
where:

  influxdb:
    host: 127.0.0.1 
    port: 8086
    database: libtrace
    username: admin
    password: admin
