# host
hostname: host1

# network interface to capture data on. 
interface: eno4

# number of packet processing threads
threads: 4

# Use local_networks to determine if a packet is inbound or outbound.
local_networks_as_direction: 1

local_networks:
  - 192.168.20.0/24
  - 2406:1E00:B910:2600::/56

# Disable libtrace HASHER_BIDIRECTIONAL hasher.
# Only disable this option if you have another mechanism for assigning packets
# of the same flow to the same thread.
enable_bidirectional_hasher: 1

# Enable debug output to stderr
debug: 0

# capture modules
foreach:

  # dns module
  dns:
    enabled: 1
    #metrics:
    #  - question
    #  - question_type
    #  - answer
    #  - rtt

  # flow stats module
  flow_statistics:
    enabled: 1
    # how often to output results in seconds
    output_interval: 30
    # enable to output counters for protcols that have not seen a packet
    output_all_protocols: 1
    metrics:
      - byte_count
      - packet_count
      - flow_count
      - ip_count

  # statistics module
  statistics:
    enabled: 0
    output_interval: 60
    metrics:
      - byte_count
      - packet_count

  # cdn statistics
  cdn_statistics:
    enabled: 0
    output_interval: 60
    cdns:
      facebook:
        - fbcdn-sphotos-b-a.akamaihd.net
        - fbcdn-sphotos-c-a.akamaihd.net
      youtube:
        - youtube.com
        - m.youtube.com
      netflix:
        - netflix.com
        - cdn.netflix.com

# output modules
where:

  influxdb:
    # Enable certificate verification
    ssl_verify_peer: 1
    host: http://192.168.20.40 
    port: 8086
    database: libtrace
    username: admin
    password: admin
