# network interface to capture data on. 
interfaces: ens18

# capture modules
foreach:

  # flow module
  flow:
    metrics:
      - src_ip
      - dst_ip
      - packet_count
      - byte_count
      - protocol

  #dns module
  dns:
    metrics:
      - question
      - question_type
      - answer
      - rtt

# output modules
where:

  influxdb:
    host: 127.0.0.1 
    port: 8086
    database: libtrace
    username: admin
    password: admin
