# network interface to capture data on. 
interface: ens18

# Use local_networks to determine is packet is inbound or outbound.
# If packet has a source and destination matching a local network will
# fallback to trace_get_direction.
local_networks_as_direction: 0
local_networks:
  - 192.168.20.0/24
  - 192.168.1.0/24

# capture modules
foreach:

  # flow module
  flow:
    metrics:
      - src_ip
      - dst_ip
      - packet_count
      - byte_count
      - protocol

  # dns module
  dns:
    metrics:
      - question
      - question_type
      - answer
      - rtt

  # flow stats module
  flow_stats:
# output modules
where:

  influxdb:
    host: 127.0.0.1 
    port: 8086
    database: libtrace
    username: admin
    password: admin
