# Hostname
hostname: hostname

# Network interface to capture data on. Any URI supported by libtrace works
# here. Supported libtrace URIs can be found at
# https://github.com/LibtraceTeam/libtrace/wiki/Supported-Trace-Formats
interface: eth0

# Number of packet processing threads. Check enable_bidirectional_hasher
# option before increasing the number of threads.
threads: 1

# Method used to determin a packets direction. i.e. inbound vs outbound.
# available options
#	DIR_METHOD_TRACE   - Use libtrace trace_get_direction API method.
#	DIR_METHOD_PORT    - Guess the direction based on server/client ports.
#	DIR_METHOD_NETWORK - Use network prefix/s from local_networks.  
direction_method: DIR_METHOD_PORT

# local networks. IPv4 and IPv6 networks are supported here.
local_networks:
  - 192.168.1.0/24

# Enable libtrace HASHER_BIDIRECTIONAL hasher.
# Only enable if you are using more than 1 packet processing thread and you
# do NOT have another mechanism for assigning packets from the same flow to
# the same Libtrace thread.
enable_bidirectional_hasher: 0

# The level of logging to output. Follow the priority mask set by syslog.h
# Each option is a priority and will generate logs for all lower priority
# options. E.g. setting to LOG_ALERT will only generate logs for LOG_ALERT
# and LOG_EMERG and setting to LOG_INFO will generate logs for LOG_INFO,
# LOG_NOTICE, LOG_WARNING, LOG_ERR, LOG_CRIT, LOG_ALERT and LOG LOG_EMERG.
# Valid options in priority order:
# LOG_EMERG
# LOG_ALERT
# LOG_CRIT
# LOG_ERR
# LOG_WARNING
# LOG_NOTICE
# LOG_INFO
# LOG_DEBUG
debug: LOG_INFO

# The location that temporary files should be written to. Temporary files are
# used when any of the enabled output plugins destinations are offline, instead
# of removing the data it is written to a temporary file. When the output
# destination is back online the data written to the temporary file is then sent
# to the output destination.
temp_path: /tmp

# capture modules
foreach:

  # dns module
  dns:
    enabled: 0
    # timeout to flush old requests that have not received a response (seconds)
    timeout_request: 20
    # how often to check for timed out requests with no response (seconds)
    timeout_check: 20

  # protocol statistics module
  protocol_statistics:
    enabled: 0
    # how often to output results (seconds)
    output_interval: 60
    metrics:
      # export in/out bytes per protocol
      - byte_count
      # export in/out packet count per protocol
      - packet_count
      # export the number of flows per protocol
      - flow_count
      # export the number unique local src/dst IPs and unique
      # external src/dst IPs
      - ip_count
      # export in/out bitrate per protocol
      - bitrate

  # flow statistics
  flow_statistics:
    enabled: 0
    # how often to output results (seconds)
    output_interval: 60
    # protocols to output flow information for. Refer to each Libprotoident
    # (https://github.com/wanduow/libprotoident) for correct names protocol names.
    # ALL can be used to monitor all protocols.
    protocols:
      - HTTP
      - HTTPS
    # protocol categories to output flow information for. Refer to Libprotoident
    # for category names. ALL can be used to monitor all categories.
    protocol_categories:
      - Remote_Access

  # statistics module
  statistics:
    enabled: 0
    output_interval: 60
    metrics:
      - byte_count
      - packet_count
      - ip4_packet_count
      - ip6_packet_count
      - tcp_packet_count
      - udp_packet_count

  # HTTP module
  http:
    enabled: 0
    # timeout to flush old requests that have not received a response (seconds)
    timeout_request: 20
    # how often to check for timed out requests with no response (seconds)
    timeout_check: 20

  # BGP module
  bgp:
    enabled: 0
    # how often to check for timed out BGP sessions (absence of update/keep alive messages
    # for the hold time (seconds).
    timeout_check: 30
    # generate and export statistics every X seconds (timeout_check determines interval)
    statistics: 1

  # SMTP module
  smtp:
    enabled: 0
    # how long to wait between responses before any state information is cleared
    timeout_request: 60
    # how often to check for expired state information
    timeout_check: 60

# filtering modules
filter:
  # The maxmind plugin will insert latitude and longitude coordinates for each
  # IP address within a result.
  maxmind:
    enabled: 0
    # Location of the maxmind database to use. Can be obtained from
    # https://dev.maxmind.com/geoip/geoip2/geolite2/
    database: /etc/bigdata/GeoLite2-City.mmdb
    metrics:
      - coordinates
      - geohash
      - city
      - country

# output modules
where:

  influxdb:
    enabled: 0
    # Enable certificate verification
    ssl_verify_peer: 1
    host: http://127.0.0.1
    port: 8086
    database: dbname
    username: dbusername
    password: dbpassword
    # Enable to send results to influxdb in batches
    batch_results: 1
    # If batching results, how many to send at a time
    batch_count: 200

  kafka:
    enabled: 0
    brokers: 127.0.0.1:9092
    topic: topicname

  elasticsearch:
    enabled: 0
    host: http://127.0.0.1
    port: 9200
    ssl_verify_peer: 1
    # Does elasticsearch require user/pass authentication (Normally when using X-Pack)
    require_user_auth: 0
    username: elasticuser
    password: elasticpassword
    # Enable to send results to elasticsearch in batches
    batch_results: 1
    # If batching results, how many to send at a time
    batch_count: 200
    
