# host
hostname: hostname

# network interface to capture data on. 
interface: eth0

# number of packet processing threads
threads: 4

# Use local_networks to determine if a packet is inbound or outbound.
# Falls back to trace_get_direction() if disabled.
local_networks_as_direction: 1

local_networks:
  - 192.168.1.0/24

# Enable libtrace HASHER_BIDIRECTIONAL hasher.
# Only enable if you do NOT have another mechanism for assigning packets
# for the same flow to the same Libtrace thread.
enable_bidirectional_hasher: 1

# Enable debug output to stderr
debug: 0

# capture modules
foreach:

  # dns module
  dns:
    enabled: 0
    # timeout to flush old requests that have not received a response (seconds)
    timeout_request: 20
    # how often to check for timed out requests with no response (seconds)
    timeout_check: 20

  # protocol statistics module
  protocol_statistics:
    enabled: 0
    # how often to output results (seconds)
    output_interval: 60
    metrics:
      - byte_count
      - packet_count
      - flow_count
      - ip_count

  # flow statistics
  flow_statistics:
    enabled: 0
    # how often to output results (seconds)
    output_interval: 60
    # protocols to output flow information for. Refer to each Libprotoident
    # (https://github.com/wanduow/libprotoident) plugins for correct names.
    protocols:
      - HTTP
      - SSH
      - HTTPS

  # statistics module
  statistics:
    enabled: 0
    output_interval: 60
    metrics:
      - byte_count
      - packet_count
      - ip4_packet_count
      - ip6_packet_count
      - tcp_packet_count
      - udp_packet_count

# output modules
where:

  influxdb:
    enabled: 0
    # Enable certificate verification
    ssl_verify_peer: 1
    host: http://127.0.0.1
    port: 8086
    database: dbname
    username: dbusername
    password: dbpassword

  kafka:
    enabled: 0
    brokers: 127.0.0.1:9092
    topic: topicname
