# host
hostname: hostname

# network interface to capture data on. 
interface: eth0

# number of packet processing threads
threads: 4

# Use local_networks to determine if a packet is inbound or outbound.
local_networks_as_direction: 1

local_networks:
  - 192.168.1.0/24

# Enable libtrace HASHER_BIDIRECTIONAL hasher.
# Only enable if you do NOT have another mechanism for assigning packets
# for the same flow to the same Libtrace thread.
enable_bidirectional_hasher: 0

# Enable debug output to stderr
debug: 0

# capture modules
foreach:

  # dns module
  dns:
    enabled: 0
    # timeout to flush old requests that have not received a response
    timeout_request: 20
    # how often to check for timed out requests with no response
    timeout_check: 20

  # protocol statistics module
  protocol_statistics:
    enabled: 0
    # how often to output results in seconds
    output_interval: 60
    metrics:
      - byte_count
      - packet_count
      - flow_count
      - ip_count

  # statistics module
  statistics:
    enabled: 0
    output_interval: 60
    metrics:
      - byte_count
      - packet_count
      - ip4_packet_count
      - ip6_packet_count
      - tcp_packet_count
      - udp_packet_count

  # cdn statistics
  cdn_statistics:
    enabled: 0
    output_interval: 60
    cdns:
      facebook:
        - fbcdn-sphotos-b-a.akamaihd.net
        - fbcdn-sphotos-c-a.akamaihd.net
      youtube:
        - youtube.com
        - m.youtube.com
      netflix:
        - netflix.com
        - cdn.netflix.com

# output modules
where:

  influxdb:
    enabled: 0
    # Enable certificate verification
    ssl_verify_peer: 1
    host: http://127.0.0.1
    port: 8086
    database: database
    username: user
    password: password

  kafka:
    enabled: 0
    brokers: 127.0.0.1:9092
    topic: topic
